name: AutoDL Power On Last

on:
  schedule:
    # 设置你想要运行脚本的时间，比如每天的 UTC 时间的 00:00 和 12:00
    - cron:  '0 20 * * *'
  workflow_dispatch:
    # 允许手动触发

jobs:
  power-on-last:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run the power_on_last function
      env:
        AUTHORIZATION: ${{ secrets.AUTHORIZATION }}
      run: |
        python main.py --power_on_last
