name: AutoDL Shutdown All

on:
  schedule:
    # '3 20 * * *' 北京时间每天凌晨 4 点 3 分 执行
    # '3 * * * *' 北京时间每小时的第 3 分执行
    - cron:  '3 * * * *'
  workflow_dispatch:
    # Allows manual triggering of the workflow

jobs:
  shutdown:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run the shutdown_all function
      env:
        AUTHORIZATION: ${{ secrets.AUTHORIZATION }}
      run: |
        python main.py --shutdown_all