name: AutoDL Keep Alive

on:
  schedule:
    # 设置你想要运行脚本的时间，比如每天的 UTC 时间的 00:00 和 12:00
    - cron:  '0 20 * * *'
  workflow_dispatch:
    # 允许手动触发

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests apscheduler

    - name: Run the change function
      env:
        AUTHORIZATION: ${{ secrets.AUTHORIZATION }}
        RUN_CHANGE_FUNCTION: true
      run: |
        python main.py
